// 获取精品歌单
export const GET_BOUTIQUE_MUSIC = 'GET_BOUTIQUE_MUSIC'
// 推荐歌单
export const MUSIC_PERSONALIZED = 'MUSIC_PERSONALIZED'
// 独家放送
export const PRIVATE_CONTENT = 'PRIVATE_CONTENT'
// 新碟上架
export const NEW_MUSIC_ALBUM = 'NEW_MUSIC_ALBUM'
// 推荐MV
export const PERSONALIZED_MV = 'PERSONALIZED_MV'
